import React, { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import * as echarts from "echarts";
import { BarChart3, Database, FileDown, FileSpreadsheet, KeyRound, LayoutDashboard, LogOut, Play, Plus, ShieldCheck, Sparkles, UploadCloud, Users } from "lucide-react";
import "./styles.css";

type SurveyQuestion = { question_id: string; text: string; question_type: string; options: string[]; research_tag: string; required: boolean };
type WrappedQuestion = { question_id: string; public_text: string; question_type: string; options: string[]; research_tag: string; source_text: string; required: boolean };
type WrappedSurvey = { survey_name: string; theme: string; tagline: string; intro: string; disclosure: string; result_types: Array<{ name: string; description: string }>; questions: WrappedQuestion[]; brand_goal: string; source: string };
type SurveySummary = { id: number; survey_name: string; theme: string; source: string; created_at: string; response_count: number };
type AnalyticsSummary = { response_count: number; result_counts: Record<string, number>; option_counts: Record<string, Record<string, number>>; research_tags: string[] };

const demoQuestionnaire = JSON.stringify([
  { id: "q1", question: "你愿意为一支日常通勤口红支付的价格是？", type: "single_choice", options: ["50元以下", "50-100元", "101-200元", "201元以上"], research_tag: "价格接受区间" },
  { id: "q2", question: "你购买口红时最看重哪些因素？", type: "multiple_choice", options: ["显色度", "持妆度", "包装设计", "品牌知名度", "成分安全"], research_tag: "核心购买因素" },
  { id: "q3", question: "你通常会在什么场景购买口红？", type: "single_choice", options: ["日常自用", "节日送礼", "约会妆容", "跟随新品趋势"], research_tag: "购买场景" },
], null, 2);

function App() {
  const [mode, setMode] = useState<"user" | "admin">("user");
  const [adminToken, setAdminToken] = useState(() => sessionStorage.getItem("admin_token") || "");
  function logout() { sessionStorage.removeItem("admin_token"); setAdminToken(""); setMode("user"); }
  return <main>
    <header className="topbar"><button className="brand" onClick={() => setMode("user")} aria-label="返回用户端">趣测智研 <span>FUN RESEARCH</span></button><nav className="main-nav"><button className={mode === "user" ? "active" : ""} onClick={() => setMode("user")}><Users size={16} /> 用户端</button><button className={mode === "admin" ? "active" : ""} onClick={() => setMode("admin")}><LayoutDashboard size={16} /> 管理后台</button>{adminToken && <button className="icon-button" onClick={logout} title="退出管理后台" aria-label="退出管理后台"><LogOut size={17} /></button>}</nav></header>
    {mode === "user" ? <UserPortal /> : adminToken ? <AdminPortal token={adminToken} /> : <AdminLogin onLogin={setAdminToken} />}
  </main>;
}

function UserPortal() {
  const [surveys, setSurveys] = useState<SurveySummary[]>([]); const [selected, setSelected] = useState<{ id: number; survey: WrappedSurvey } | null>(null); const [answers, setAnswers] = useState<Record<string, unknown>>({}); const [result, setResult] = useState<{ name: string; description: string } | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { void loadPublicSurveys(); }, []);
  async function loadPublicSurveys() { try { const data = await fetchJson<{ items: SurveySummary[] }>("/api/public/surveys"); setSurveys(data.items); if (data.items.length) await openSurvey(data.items[0].id); } catch (error) { setMessage(getErrorMessage(error)); } }
  async function openSurvey(id: number) { setLoading(true); setMessage(""); try { const data = await fetchJson<{ id: number; survey: WrappedSurvey }>(`/api/public/surveys/${id}`); setSelected(data); setAnswers({}); setResult(null); } catch (error) { setMessage(getErrorMessage(error)); } finally { setLoading(false); } }
  async function submitAnswers() { if (!selected) return; if (!isSurveyComplete(selected.survey, answers)) { setMessage("请完成所有必答题后再提交。"); return; } setLoading(true); setMessage(""); try { const data = await postJson<{ result: { name: string; description: string } }>("/api/responses", { survey_id: selected.id, answers }); setResult(data.result); setMessage("答卷已提交，感谢你的参与。"); } catch (error) { setMessage(getErrorMessage(error)); } finally { setLoading(false); } }
  const completion = useMemo(() => { if (!selected) return 0; const required = selected.survey.questions.filter((question) => question.required); const answered = required.filter((question) => isAnswerPresent(answers[question.question_id])).length; return required.length ? Math.round((answered / required.length) * 100) : 100; }, [answers, selected]);
  return <><section className="hero compact-hero"><div><p className="eyebrow">INTERACTIVE RESEARCH</p><h1>用一分钟，完成一次有趣的市场调研。</h1><p>选择一份测评，按直觉作答。你的答案将帮助品牌更好地理解真实需求。</p></div><div className="heroPanel user-hero-panel"><Sparkles size={23} /><strong>轻松作答，真实反馈</strong><span>本页面不收集姓名、手机号等直接身份信息。</span></div></section>{message && <div className="notice">{message}</div>}<section className="user-layout"><aside className="survey-list panel"><div className="section-heading"><div><p className="eyebrow">SURVEYS</p><h2>可参与的测评</h2></div><Database size={20} /></div>{!surveys.length ? <Empty text="暂无已发布的测评，请由管理后台先生成一个。" /> : surveys.map((item) => <button key={item.id} className={`survey-item ${selected?.id === item.id ? "selected" : ""}`} onClick={() => void openSurvey(item.id)}><span>{item.theme}</span><strong>{item.survey_name}</strong><small>{item.response_count} 人已完成</small></button>)}</aside><section className="testSurface user-surface">{!selected ? <Empty text="请选择左侧测评开始体验。" /> : <><p className="eyebrow">{selected.survey.theme}</p><h2>{selected.survey.survey_name}</h2><p className="lead">{selected.survey.tagline}</p><p className="intro">{selected.survey.intro}</p><div className="disclosure">{selected.survey.disclosure}</div><div className="progress-label"><span>完成进度</span><b>{completion}%</b></div><div className="progress"><span style={{ width: `${completion}%` }} /></div>{selected.survey.questions.map((question, index) => <QuestionInput key={question.question_id} index={index + 1} question={question} value={answers[question.question_id]} onChange={(value) => setAnswers({ ...answers, [question.question_id]: value })} />)}<button className="primary wide" onClick={() => void submitAnswers()} disabled={loading || completion < 100}><Play size={18} /> {loading ? "提交中..." : "查看我的结果"}</button>{result && <div className="result"><p className="eyebrow">YOUR RESULT</p><h3>{result.name}</h3><p>{result.description}</p></div>}</>}</section></section></>;
}

function AdminLogin({ onLogin }: { onLogin: (token: string) => void }) {
  const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function login(event: React.FormEvent) { event.preventDefault(); setLoading(true); setMessage(""); try { const data = await postJson<{ token: string }>("/api/admin/login", { password }); sessionStorage.setItem("admin_token", data.token); onLogin(data.token); } catch (error) { setMessage(getErrorMessage(error)); } finally { setLoading(false); } }
  return <section className="login-wrap"><form className="login-panel" onSubmit={login}><div className="login-icon"><ShieldCheck size={25} /></div><p className="eyebrow">RESEARCH CONSOLE</p><h1>管理后台</h1><p>登录后管理问卷包装、查看题目映射和分析答卷数据。</p><label htmlFor="admin-password">后台密码</label><div className="password-input"><KeyRound size={17} /><input id="admin-password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="请输入后台密码" autoFocus /></div>{message && <div className="form-error">{message}</div>}<button className="primary wide" type="submit" disabled={loading || !password}>{loading ? "登录中..." : "进入管理后台"}</button></form></section>;
}

function AdminPortal({ token }: { token: string }) {
  const [active, setActive] = useState<"overview" | "create" | "mapping">("overview"); const [surveys, setSurveys] = useState<SurveySummary[]>([]); const [selectedId, setSelectedId] = useState<number | null>(null); const [survey, setSurvey] = useState<WrappedSurvey | null>(null); const [summary, setSummary] = useState<AnalyticsSummary | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function loadSurveys() { try { const data = await adminFetchJson<{ items: SurveySummary[] }>("/api/surveys", token); setSurveys(data.items); if (data.items.length && !selectedId) await selectSurvey(data.items[0].id); } catch (error) { setMessage(getErrorMessage(error)); } }
  async function selectSurvey(id: number) { setLoading(true); setMessage(""); try { const [surveyData, analyticsData] = await Promise.all([adminFetchJson<{ payload: WrappedSurvey }>(`/api/surveys/${id}`, token), adminFetchJson<{ summary: AnalyticsSummary }>(`/api/analytics/${id}`, token)]); setSelectedId(id); setSurvey(surveyData.payload); setSummary(analyticsData.summary); } catch (error) { setMessage(getErrorMessage(error)); } finally { setLoading(false); } }
  useEffect(() => { void loadSurveys(); }, []);
  function onCreated(id: number, createdSurvey: WrappedSurvey) { setSurveys((items) => [{ id, survey_name: createdSurvey.survey_name, theme: createdSurvey.theme, source: createdSurvey.source, created_at: new Date().toISOString(), response_count: 0 }, ...items]); setSelectedId(id); setSurvey(createdSurvey); setSummary({ response_count: 0, result_counts: {}, option_counts: {}, research_tags: createdSurvey.questions.map((question) => question.research_tag).filter(Boolean) }); setActive("mapping"); }
  return <><section className="admin-head"><div><p className="eyebrow">ADMINISTRATION</p><h1>研究数据工作台</h1><p>管理互动问卷，追踪研究字段，导出可提交的调研报告。</p></div><div className="admin-status"><span className="status-dot" /> 本地数据库已连接</div></section>{message && <div className="notice">{message}</div>}<div className="admin-shell"><aside className="admin-sidebar"><button className={active === "overview" ? "active" : ""} onClick={() => setActive("overview")}><LayoutDashboard size={17} /> 数据总览</button><button className={active === "create" ? "active" : ""} onClick={() => setActive("create")}><Plus size={17} /> 创建包装</button><button className={active === "mapping" ? "active" : ""} onClick={() => setActive("mapping")} disabled={!survey}><Database size={17} /> 题目映射</button><div className="sidebar-divider" /><p>已保存问卷</p>{surveys.map((item) => <button key={item.id} className={`sidebar-survey ${selectedId === item.id ? "selected" : ""}`} onClick={() => void selectSurvey(item.id)}><span>{item.theme}</span>{item.survey_name}</button>)}</aside><section className="admin-content">{active === "create" ? <CreateWorkspace token={token} onCreated={onCreated} /> : active === "mapping" && survey ? <MappingView survey={survey} /> : <Dashboard survey={survey} summary={summary} surveyCount={surveys.length} loading={loading} token={token} selectedId={selectedId} />}</section></div></>;
}

function CreateWorkspace({ token, onCreated }: { token: string; onCreated: (id: number, survey: WrappedSurvey) => void }) {
  const [sourceText, setSourceText] = useState(demoQuestionnaire); const [questions, setQuestions] = useState<SurveyQuestion[]>([]); const [brandGoal, setBrandGoal] = useState("了解年轻用户对日常通勤口红的价格接受程度和购买偏好"); const [themeHint, setThemeHint] = useState("恋爱象限里的口红人格"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function parseSurvey() { setLoading(true); setMessage(""); try { const data = await adminPostJson<{ questions: SurveyQuestion[] }>("/api/surveys/parse", { content: sourceText, file_name: sourceText.trim().startsWith("[") ? "survey.json" : "survey.csv" }, token); setQuestions(data.questions); setMessage(`已识别 ${data.questions.length} 道题。`); } catch (error) { setMessage(getErrorMessage(error)); } finally { setLoading(false); } }
  async function uploadFile(file: File) { setLoading(true); setMessage(""); try { const formData = new FormData(); formData.append("file", file); const response = await fetch("/api/surveys/upload", { method: "POST", headers: { "X-Admin-Token": token }, body: formData }); if (!response.ok) throw new Error(await readError(response)); const data = (await response.json()) as { questions: SurveyQuestion[] }; setQuestions(data.questions); setMessage(`已从文件识别 ${data.questions.length} 道题。`); } catch (error) { setMessage(getErrorMessage(error)); } finally { setLoading(false); } }
  async function wrapSurvey() { setLoading(true); setMessage(""); try { const data = await adminPostJson<{ id: number; survey: WrappedSurvey }>("/api/surveys/wrap", { questions, brand_goal: brandGoal, theme_hint: themeHint }, token); onCreated(data.id, data.survey); } catch (error) { setMessage(getErrorMessage(error)); } finally { setLoading(false); } }
  return <section><div className="page-title"><div><p className="eyebrow">CREATE A STUDY</p><h2>创建互动包装</h2><p>导入原始问卷，使用线上 Responses API 生成可参与的测评主题。</p></div><Sparkles size={26} /></div>{message && <div className="notice">{message}</div>}<div className="workspace two"><div className="panel"><div className="section-heading"><h2><UploadCloud size={19} /> 导入问卷</h2><span className="step-number">01</span></div><label className="fileBox"><input type="file" accept=".csv,.json" onChange={(event) => event.target.files?.[0] && void uploadFile(event.target.files[0])} />选择 CSV / JSON 文件</label><textarea value={sourceText} onChange={(event) => setSourceText(event.target.value)} /><button onClick={() => void parseSurvey()} disabled={loading}>解析问卷</button></div><div className="panel"><div className="section-heading"><h2><Sparkles size={19} /> AI 包装设定</h2><span className="step-number">02</span></div><label>调研目标</label><textarea className="short" value={brandGoal} onChange={(event) => setBrandGoal(event.target.value)} /><label>互动主题</label><input value={themeHint} onChange={(event) => setThemeHint(event.target.value)} /><button className="primary" onClick={() => void wrapSurvey()} disabled={!questions.length || !brandGoal.trim() || !themeHint.trim() || loading}>生成互动包装</button><QuestionTable questions={questions} /></div></div></section>;
}

function Dashboard({ survey, summary, surveyCount, loading, token, selectedId }: { survey: WrappedSurvey | null; summary: AnalyticsSummary | null; surveyCount: number; loading: boolean; token: string; selectedId: number | null }) {
  if (!survey || !summary) return <Empty text={loading ? "正在读取数据..." : surveyCount ? "请选择一份问卷查看分析。" : "暂无问卷，请先创建互动包装。"} />;
  return <section><div className="page-title"><div><p className="eyebrow">OVERVIEW / {survey.theme}</p><h2>{survey.survey_name}</h2><p>{survey.tagline}</p></div><span className="source-badge"><span className="status-dot" /> AI 已生成</span></div><div className="metrics"><Metric label="有效答卷" value={summary.response_count} icon={<Users size={18} />} /><Metric label="研究字段" value={summary.research_tags.length} icon={<Database size={18} />} /><Metric label="包装题目" value={survey.questions.length} icon={<Sparkles size={18} />} /><Metric label="结果类型" value={Object.keys(summary.result_counts).length} icon={<BarChart3 size={18} />} /></div><div className="dashboard-grid"><ChartCard title="结果类型分布" subtitle="了解不同趣味结果的占比" option={resultChartOption(summary.result_counts)} /><ChartCard title="答卷完成概况" subtitle="当前包装方案的有效回收量" option={completionChartOption(summary.response_count)} /></div><div className="chart-section"><div className="section-heading"><div><h3>研究选项分布</h3><p>数据按原始题目 ID 与研究标签聚合</p></div><BarChart3 size={20} /></div>{survey.questions.map((question) => <ChartCard key={question.question_id} compact title={question.research_tag || question.source_text} subtitle={`${question.question_id} · ${question.question_type}`} option={barChartOption(question, summary.option_counts[question.question_id] || {})} />)}</div><div className="export-row"><button onClick={() => selectedId && void downloadReport(`/api/analytics/${selectedId}/excel`, token, "fun_research_data.xlsx")}><FileSpreadsheet size={17} /> 导出 Excel 明细</button><button onClick={() => selectedId && void downloadReport(`/api/analytics/${selectedId}/pdf`, token, "fun_research_report.pdf")}><FileDown size={17} /> 导出 PDF 报表</button></div></section>;
}

function MappingView({ survey }: { survey: WrappedSurvey }) { return <section><div className="page-title"><div><p className="eyebrow">TRACEABLE MAPPING</p><h2>原题与互动题对照</h2><p>每道题通过 question_id 保持研究语义可追踪，包装文本和原始字段分开保存。</p></div><ShieldCheck size={26} /></div><div className="mapping-list">{survey.questions.map((question, index) => <article className="mapping-row" key={question.question_id}><div className="mapping-index">{String(index + 1).padStart(2, "0")}</div><div><span className="mapping-label">原始研究题目 · {question.research_tag || "未设置标签"}</span><h3>{question.source_text}</h3><small>{question.question_id} · {question.question_type}</small></div><div className="mapping-arrow">→</div><div><span className="mapping-label accent">用户体验题面</span><h3>{question.public_text}</h3><small>{question.options.length ? `${question.options.length} 个选项` : "文本回答"}</small></div></article>)}</div></section>; }
function QuestionTable({ questions }: { questions: SurveyQuestion[] }) { if (!questions.length) return <p className="muted">尚未解析问卷。</p>; return <div className="table">{questions.map((item) => <div key={item.question_id}><b>{item.question_id}</b><span>{item.text}</span><em>{item.research_tag || "未设置标签"}</em></div>)}</div>; }
function QuestionInput({ index, question, value, onChange }: { index: number; question: WrappedQuestion; value: unknown; onChange: (value: unknown) => void }) { return <div className="question"><div className="question-meta"><span>{String(index).padStart(2, "0")}</span>{question.required && <em>必答</em>}</div><h3>{question.public_text}</h3>{question.question_type === "multiple_choice" ? <div className="options">{question.options.map((option) => { const selected = Array.isArray(value) && value.includes(option); return <button className={selected ? "selected" : ""} key={option} onClick={() => { const current = Array.isArray(value) ? value : []; onChange(selected ? current.filter((item) => item !== option) : [...current, option]); }}>{option}</button>; })}</div> : question.question_type === "text" ? <input value={String(value || "")} onChange={(event) => onChange(event.target.value)} /> : <div className="options">{(question.options.length ? question.options : ["非常不像", "有点像", "很像"]).map((option) => <button className={value === option ? "selected" : ""} key={option} onClick={() => onChange(option)}>{option}</button>)}</div>}</div>; }
function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="metric"><span className="metric-icon">{icon}</span><span>{label}</span><strong>{value}</strong></div>; }
function ChartCard({ title, subtitle, option, compact = false }: { title: string; subtitle: string; option: echarts.EChartsOption; compact?: boolean }) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!ref.current) return; const chart = echarts.init(ref.current); chart.setOption(option); const resize = () => chart.resize(); window.addEventListener("resize", resize); return () => { window.removeEventListener("resize", resize); chart.dispose(); }; }, [option]); return <div className={`chart-card ${compact ? "compact" : ""}`}><div className="chart-card-title"><div><h3>{title}</h3><p>{subtitle}</p></div><BarChart3 size={18} /></div><div className="chart-canvas" ref={ref} /></div>; }
function resultChartOption(counts: Record<string, number>): echarts.EChartsOption { return { color: ["#2467e8", "#32a287", "#f29d49", "#db5873", "#7b61c9"], tooltip: { trigger: "item" }, legend: { bottom: 0, type: "scroll" }, series: [{ type: "pie", radius: ["42%", "68%"], center: ["50%", "44%"], label: { formatter: "{b}\n{d}%" }, data: Object.entries(counts).map(([name, value]) => ({ name, value })) }] }; }
function completionChartOption(count: number): echarts.EChartsOption { return { series: [{ type: "gauge", startAngle: 90, endAngle: -270, radius: "78%", pointer: { show: false }, progress: { show: true, width: 15, itemStyle: { color: "#2467e8" } }, axisLine: { lineStyle: { width: 15, color: [[1, "#e4e9f1"]] } }, axisTick: { show: false }, splitLine: { show: false }, axisLabel: { show: false }, detail: { valueAnimation: true, formatter: `${count}\n有效答卷`, fontSize: 20, lineHeight: 30, color: "#18212b" }, data: [{ value: count, name: "" }] }] }; }
function barChartOption(question: WrappedQuestion, counts: Record<string, number>): echarts.EChartsOption { const labels = question.options.length ? question.options : Object.keys(counts); return { color: ["#2467e8"], grid: { left: 20, right: 28, top: 12, bottom: 10, containLabel: true }, tooltip: { trigger: "axis", axisPointer: { type: "shadow" } }, xAxis: { type: "value", minInterval: 1 }, yAxis: { type: "category", data: labels, axisLabel: { width: 150, overflow: "truncate" } }, series: [{ type: "bar", data: labels.map((label) => counts[label] || 0), barMaxWidth: 18, itemStyle: { borderRadius: [0, 4, 4, 0] }, label: { show: true, position: "right" } }] }; }
function isAnswerPresent(value: unknown) { return Array.isArray(value) ? value.length > 0 : typeof value === "string" ? value.trim() !== "" : value !== undefined && value !== null; }
function isSurveyComplete(survey: WrappedSurvey, answers: Record<string, unknown>) { return survey.questions.every((question) => !question.required || isAnswerPresent(answers[question.question_id])); }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
async function postJson<T>(url: string, body: unknown): Promise<T> { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await readError(response)); return response.json(); }
async function adminPostJson<T>(url: string, body: unknown, token: string): Promise<T> { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json", "X-Admin-Token": token }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await readError(response)); return response.json(); }
async function fetchJson<T>(url: string): Promise<T> { const response = await fetch(url); if (!response.ok) throw new Error(await readError(response)); return response.json(); }
async function adminFetchJson<T>(url: string, token: string): Promise<T> { const response = await fetch(url, { headers: { "X-Admin-Token": token } }); if (!response.ok) throw new Error(await readError(response)); return response.json(); }
async function readError(response: Response) { try { const data = (await response.json()) as { detail?: string }; return data.detail || "请求失败"; } catch { return `请求失败（HTTP ${response.status}）`; } }
async function downloadReport(url: string, token: string, fileName: string) { const response = await fetch(url, { headers: { "X-Admin-Token": token } }); if (!response.ok) throw new Error(await readError(response)); const blob = await response.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = fileName; link.click(); URL.revokeObjectURL(link.href); }
function getErrorMessage(error: unknown) { return error instanceof Error ? error.message : "发生未知错误"; }
createRoot(document.getElementById("root")!).render(<App />);
